package weddingsite.shared;

public enum ActionType {
	LOGIN,
	GETATTENDANCELISTS,
	GETATTENDEES,
	ADDATTENDANCELIST,
	ADDATTENDEE,
	DELETEATTENDEE,
	EDITATTENDEE,
	GETSEATINGCHARTS,
	GETTABLES,
	GETPEOPLEATTABLE,
	ADDSEATINGCHART,
	EDITTABLE,
	ADDTABLE,
	DELETETABLE,
	DELETEATTENDANCELIST,
	EDITATTENDANCELIST,
	DELETESEATINGCHART,
	EDITSEATINGCHART,
}
